name: intera
description: Intera App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Framework para gerência de estado/injeção de dependência/navegação, etc...
  get: ^4.0.0-nullsafety.2
  # Package para gerenciar os arquivos locais
  get_storage: ^2.0.1
  # Framework para responsividade
  flutter_screenutil: ^5.0.0-nullsafety.11
  # Package para animações
  animate_do: ^2.0.0
  # Package para Formatações de textos
  intl: ^0.17.0
  # Package para obter imagens da galeria
  image_picker: ^0.7.3
  # Report's de Erros
  firebase_crashlytics: ^1.0.0
  # Firebase Core
  firebase_core: ^1.0.2
  # Autenticação com Firebase
  firebase_auth: ^1.0.1
  
  flutter:
    sdk: flutter

dev_dependencies:
  # Package para mock's nos testes
  mocktail: ^0.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/Circular-Std-Book.ttf
          weight: 400
        - asset: assets/fonts/Circular-Std-Medium.ttf
          weight: 500
        - asset: assets/fonts/Circular-Std-Bold.ttf
          weight: 700